// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buzkdesayosvvgftnwuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1emtkZXNheW9zdnZnZnRud3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MTY0MDAsImV4cCI6MjA1MjE5MjQwMH0.2gyRYYkk6FV8o4YOI3FSH7XPko_7C_LzH_zh0pPrEQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);